name: Setup package 📝
on:
  workflow_dispatch:
  push:
    branches:
    - main
    
jobs:
  Setup:
    runs-on: ubuntu-latest
    
    env:
      # This need to respect the Unity nomenclature (see : https://docs.unity3d.com/Manual/cus-naming.html)
      # Previous name (back slash to include special character):
      PrevAuthorNameField: \[YourAuthorName\]
      PrevCompanyNameField: \[YourCompany\]
      PrevPackageNameField: \[YourPackageName\]
      PrevGitURLField: \[YourHTTPSGit\]
      PrevPackageDisplayNameField: \[YourPackageDisplayName\]
      # Your current settings :
      AuthorNameField: ${{github.repository_owner}}
      PackageNameField: ${{github.event.repository.name}}
      GitURLField: ${{github.server_url}}/${{github.repository}}.git
    
    steps:
      ###########################
      #         Checkout        #
      ###########################
    - name: Checkout project
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
      ##########################
      #     Replace field      #
      ##########################      
    - name: Replace name
      run: |
        echo ""
        echo "#########################"
        echo "#    Replace field     #"
        echo "#########################"
        echo ""
        echo ""
        
        LowercaseProjectName="$(echo $PackageNameField | sed 's/[A-Z]/-&/g;s/^-//' | tr '[A-Z]' '[a-z]')"
        LowercaseCompanyNameField="$(echo $AuthorNameField | sed 's/[A-Z]/-&/g;s/^-//' | tr '[A-Z]' '[a-z]')"
        
        find . -type f -name "*" ! -path "./.github/*" ! -path "./.git/*" ! -name ".gitignore" | while read FILE ; do
          sed -i -e "s/$PrevCompanyNameField/$LowercaseCompanyNameField/" -e "s/$PrevPackageNameField/$LowercaseProjectName/" ${FILE}
          newfile="$(echo ${FILE} |sed -e "s/$PrevCompanyNameField/$LowercaseCompanyNameField/" -e "s/$PrevPackageNameField/$LowercaseProjectName/")";
          if [ "${FILE}" != "${newfile}" ]; then
              echo "Rename ${FILE} to ${newfile}"
              mv "${FILE}" "${newfile}" ;
          fi
        done
        
        echo "Set project display name: $PackageNameField"
        sed -i "s|$PrevPackageDisplayNameField|$PackageNameField|" package.json
        
        echo "Set author : $AuthorNameField"
        sed -i "s|$PrevAuthorNameField|$AuthorNameField|" package.json
        
        echo "Add repository URL: $GitURLField"
        sed -i "s|$PrevGitURLField|$GitURLField|" package.json
        
        echo "Replace badge in reamde"
        sed -i -e "s/OpenSourceUnityPackage/$AuthorNameField/" -e "s/PackageTemplate/$PackageNameField/" README.md
        
      ################################
      #     Remove setup action      #
      ################################      
    - name: Remove setup action
      run: |
        rm .github/workflows/setup.yml
      
      ###########################
      #         Commit          #
      ###########################
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add changes"
        
      #########################
      #         Push          #
      #########################
    - name: Push changes
      uses: ad-m/github-push-action@a3fd843e49cd58d296bdd2431c4853569a1b900f #Use specific commit for stability
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
